### ISSUE TITLE
Arquivar arqtrad

### ISSUE THREAD

**Issue by p3palazzo** [dmcpatrimonio/arqtrad#35]
Depois de resolver:

- [x] dmcpatrimonio/classico-trad-ecletico#1
- [x] dmcpatrimonio/classico-trad-ecletico#2
- [ ] dmcpatrimonio/classico-trad-ecletico-pibic21#1
- [ ] dmcpatrimonio/classico-trad-ecletico-pibic21#2
- [ ] dmcpatrimonio/6enanparq#1
- [ ] dmcpatrimonio/6enanparq#2
- [ ] dmcpatrimonio/6enanparq#3
